<table>
    <tr>
        <th>
            <?= __("Id")?>
        </th>
        <th>
            <?= __("Title")?>
        </th>
        <th>
            <?= __("Content")?>
        </th>
    </tr>
    <?php
    $blogs = $block->getBlogs();

    foreach ($blogs as $blog) {?>
    <tr>
        <td>
            <?= $blog->getId()?>
        </td>
        <td>
            <?= $blog->getTitle()?>
        </td>
        <td>
            <?= substr($blog->getContent(), 0, 20).'...'?>
        </td>
    </tr>
    <?php } ?>
</table>